// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	DetailRequest
	CreateRequest
	DetailResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DetailRequest struct {
	Iid string `protobuf:"bytes,1,opt,name=iid" json:"iid,omitempty"`
}

func (m *DetailRequest) Reset()                    { *m = DetailRequest{} }
func (m *DetailRequest) String() string            { return proto1.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()               {}
func (*DetailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DetailRequest) GetIid() string {
	if m != nil {
		return m.Iid
	}
	return ""
}

type CreateRequest struct {
	Iid      string            `protobuf:"bytes,1,opt,name=iid" json:"iid,omitempty"`
	Name     string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Icon     string            `protobuf:"bytes,3,opt,name=icon" json:"icon,omitempty"`
	Props    map[string]string `protobuf:"bytes,4,rep,name=props" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreateAt string            `protobuf:"bytes,5,opt,name=createAt" json:"createAt,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetIid() string {
	if m != nil {
		return m.Iid
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *CreateRequest) GetProps() map[string]string {
	if m != nil {
		return m.Props
	}
	return nil
}

func (m *CreateRequest) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

type DetailResponse struct {
	Iid      string            `protobuf:"bytes,1,opt,name=iid" json:"iid,omitempty"`
	Name     string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Icon     string            `protobuf:"bytes,3,opt,name=icon" json:"icon,omitempty"`
	Props    map[string]string `protobuf:"bytes,4,rep,name=props" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreateAt string            `protobuf:"bytes,5,opt,name=createAt" json:"createAt,omitempty"`
}

func (m *DetailResponse) Reset()                    { *m = DetailResponse{} }
func (m *DetailResponse) String() string            { return proto1.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()               {}
func (*DetailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DetailResponse) GetIid() string {
	if m != nil {
		return m.Iid
	}
	return ""
}

func (m *DetailResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetailResponse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *DetailResponse) GetProps() map[string]string {
	if m != nil {
		return m.Props
	}
	return nil
}

func (m *DetailResponse) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func init() {
	proto1.RegisterType((*DetailRequest)(nil), "proto.DetailRequest")
	proto1.RegisterType((*CreateRequest)(nil), "proto.CreateRequest")
	proto1.RegisterType((*DetailResponse)(nil), "proto.DetailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserClient interface {
	Detail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*DetailResponse, error)
}

type userClient struct {
	c           client.Client
	serviceName string
}

func NewUserClient(serviceName string, c client.Client) UserClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proto"
	}
	return &userClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userClient) Detail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error) {
	req := c.c.NewRequest(c.serviceName, "User.Detail", in)
	out := new(DetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*DetailResponse, error) {
	req := c.c.NewRequest(c.serviceName, "User.Create", in)
	out := new(DetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Detail(context.Context, *DetailRequest, *DetailResponse) error
	Create(context.Context, *CreateRequest, *DetailResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&User{hdlr}, opts...))
}

type User struct {
	UserHandler
}

func (h *User) Detail(ctx context.Context, in *DetailRequest, out *DetailResponse) error {
	return h.UserHandler.Detail(ctx, in, out)
}

func (h *User) Create(ctx context.Context, in *CreateRequest, out *DetailResponse) error {
	return h.UserHandler.Create(ctx, in, out)
}

func init() { proto1.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x8a, 0x5c, 0xbc, 0x2e, 0xa9,
	0x25, 0x89, 0x99, 0x39, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x02, 0x5c, 0xcc, 0x99,
	0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0xd2, 0x35, 0x46, 0x2e, 0x5e,
	0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0x54, 0x9c, 0x6a, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x98, 0xc0, 0x42, 0x60, 0x36, 0x48, 0x2c, 0x33, 0x39, 0x3f, 0x4f, 0x82, 0x19, 0x22, 0x06,
	0x62, 0x0b, 0x99, 0x72, 0x81, 0xec, 0x2d, 0x28, 0x96, 0x60, 0x51, 0x60, 0xd6, 0xe0, 0x36, 0x92,
	0x87, 0x38, 0x46, 0x0f, 0xc5, 0x78, 0xbd, 0x00, 0x90, 0x0a, 0xd7, 0xbc, 0x92, 0xa2, 0xca, 0x20,
	0x88, 0x6a, 0x21, 0x29, 0x2e, 0x8e, 0x64, 0xb0, 0x12, 0xc7, 0x12, 0x09, 0x56, 0xb0, 0x71, 0x70,
	0xbe, 0x94, 0x05, 0x17, 0x17, 0x42, 0x03, 0xc8, 0x69, 0xd9, 0xa9, 0x95, 0x30, 0xa7, 0x65, 0xa7,
	0x56, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xc2, 0xdc, 0x06, 0xe1, 0x58, 0x31, 0x59,
	0x30, 0x2a, 0xdd, 0x60, 0xe4, 0xe2, 0x83, 0x79, 0xbe, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x95, 0x02,
	0x9f, 0x99, 0xa1, 0xfa, 0x4c, 0x01, 0xea, 0x33, 0x54, 0xf3, 0xe9, 0xe5, 0x35, 0xa3, 0x0a, 0x2e,
	0x96, 0xd0, 0xe2, 0xd4, 0x22, 0x21, 0x73, 0x2e, 0x36, 0x88, 0x0b, 0x84, 0x44, 0xd0, 0x1c, 0x04,
	0x0e, 0x6a, 0x29, 0x51, 0xac, 0xce, 0x54, 0x62, 0x00, 0x69, 0x84, 0x44, 0x0a, 0x5c, 0x23, 0x4a,
	0x1c, 0xe1, 0xd4, 0x98, 0xc4, 0x06, 0x16, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x27, 0x17,
	0x6c, 0x06, 0x6c, 0x02, 0x00, 0x00,
}
